project:
  type: website
  output-dir: docs

website:
  title: "Limin Huang"
  navbar:
    right:
      - text: About
        href: index.qmd
      - blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/huang-limin
      - icon: github
        href: https://github.com/LiminMHuang
      - icon: twitter
        href: https://x.com/LiminMHuang
format:
  html:
    theme: cosmo
    css: styles.css



